# This file is machine-generated - editing it directly is not advised

[[ASTParser]]
deps = ["ProxyInterface", "SimpleMatch", "StructEquality"]
path = "D:\\ProjectsJulia\\\\ASTParser\\\\"
uuid = "3311a090-b55d-11e9-176d-dbdfc6a88253"
version = "0.1.0"

[[DataTypesBasic]]
path = "D:\\ProjectsJulia\\\\DataTypesBasic\\\\"
uuid = "83eed652-29e8-11e9-12da-a7c29d64ffc9"
version = "0.1.0"

[[ProxyInterface]]
path = "D:\\ProjectsJulia\\\\ProxyInterface\\\\"
uuid = "90c4b210-f34a-11e9-1a87-5d0d3aaf0cab"
version = "0.1.0"

[[SimpleMatch]]
path = "D:\\ProjectsJulia\\\\SimpleMatch\\\\"
uuid = "a3ae8450-d22f-11e9-3fe0-77240e25996f"
version = "0.1.0"

[[StructEquality]]
deps = ["SimpleMatch"]
path = "D:\\ProjectsJulia\\\\StructEquality\\\\"
uuid = "6ec83bb0-ed9f-11e9-3b4c-2b04cb4e219c"
version = "0.1.0"
